version: '3.1'

services:
    pyprotoc:
        build:
        context: .
        dockerfile: Dockerfile
        command: python -m grpc_tools.protoc -I. --python_out=./build/gen/ --grpc_python_out=./build/gen/ file.proto
        volumes:
        - .:/src